sudo: false
language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
before_deploy:
- npm run -s build
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: git
  on:
    branch: master
  api_key:
    secure: QJcKiL99mbF3ba7UiRsWuRad9D/G3p0J6jlMT2JJg6co0IXBVm2sQLAOpBCRyTnMPiHw2aUHzWpFTm/Doq4daOkKFLwX4PmazSWu8E5v5RBUnY3x60/tMcoNwfy8PwZSOhz4XdvNqr1YKbdDlkdPqGaKKGsqqCv1NaT0uHbHI/3MKt752E17/b0/ppHMloQJ1SoEFf8eOYfuhQTcGbIeZXqqaTOuSGdmc0+TxOqXLzXEv6Wsk7LpGm6mBTXbkvxue0sViQKMEJNgb+Twpwrd3wQdhO+wbruxVNCBMhiKYvJnDrNVyOtsUtCvPJdRi5ar17WuFPlhPnpN601kvj5tMXQFCiP0zsb/TcOR3J3wqhq5bJoq0pVn+LNBnxs78kyD/tNi0tOdM5yBXN/2V/6UEof7/tPzrCGvAnEQ9ttxjCqwqiZVs/ytPZRtkmSHfVf2OpyyGhu+7KmnXDd99mp8GQsfFHuI2KB9hUvv+0/IVcvcBWNNq/jA2WmPVeWViw1zFTfzf4PdnfEKIrErdIYQxecH9W15Ey4gEINTY/b09MM9YhHWOOFw7AgdWBLSr5M44nf/ujIcqXcSOU26arlLd/paDPZyeWshKQrogwhTmnUmu02GhAPqViVPCYMwFggGUZk3RkMI271hunGJamIRx+zp/N2NzQvuy7bS7nRqL50=
  run: 
   - "npm install --production"
   - restart